name: Now TV M3U Guncelle

on:
  schedule:
    # Her 2 saatte bir çalışır (UTC)
    - cron: "0 */2 * * *"
  workflow_dispatch: # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest
    # Yazma izni (Push hatası almamak için kritik)
    permissions:
      contents: write

    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Scripti Calistir
        run: python nowdizi.py

      - name: Guncellenen Dosyayi Kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Now_Diziler.m3u
          # Değişiklik yoksa hata vermemesi için 'exit 0'
          git commit -m "Otomatik Güncelleme: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
