update.yml içeriği name: Now TV M3U Guncelle

on:
  schedule:
    # Her 5 saatte bir çalışır (UTC zaman dilimine göre)
    - cron: "0 */5 * * *"
  workflow_dispatch: # İstediğinde manuel başlatabilmen için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yukle
        run: |
          pip install requests

      - name: Scripti Calistir
        run: python nowdizi.py

      - name: Guncellenen Dosyayi Kaydet
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add Now_Diziler.m3u
          git commit -m "Otomatik Güncelleme: $(date)" || echo "Değişiklik yok"
          git push
